# Generated by Django 4.1.4 on 2023-02-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User1', models.CharField(max_length=255)),
                ('User2', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='author',
            old_name='age',
            new_name='Author1',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='Author2',
        ),
        migrations.RemoveField(
            model_name='author',
            name='contract',
        ),
    ]
