# Generated by Django 4.1.4 on 2023-02-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_user_rename_age_author_author1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
