# Generated by Django 4.1.4 on 2023-02-03 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
