# Generated by Django 4.1.4 on 2023-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_post_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractBaseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
