# Generated by Django 4.1.4 on 2023-02-04 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_abstractbaseuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AbstractBaseUser',
        ),
    ]
