# Generated by Django 4.1.4 on 2023-02-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
