# Generated by Django 4.1.4 on 2023-02-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.user')),
            ],
        ),
    ]
